# pandas e csv

## Resumo

Quase sempre quando formos "ler" um arquivo csv, vamos usar o pandas. É prático e bem eficiente.

## Funcionamento

Forma mais básica: (muitas vezes não usaremos a forma mais básica)
dataframe = pd.read_csv(arquivo_com_extensao)

- Vamos ler um arquivo real, com a Base de Dados de Vendas da Empresa "Contoso"

In [2]:
import pandas as pd

vendas_df = pd.read_csv('Contoso - Cadastro Produtos.csv')

print(vendas_df)

                                                                Nome da Marca;Tipo;Custo Unitario;Preco Unitario;ID Produto;Categoria
Contoso;Econômico;10        69;20                                                 96;873;Acessório para Computador
Contoso;Econômico;6         63;13;879;Acessório para Computador                                                NaN
                            63;13;880;Acessório para Computador                                                NaN
                            63;13;881;Acessório para Computador                                                NaN
                            63;13;882;Acessório para Computador                                                NaN
...                                                                                                            ...
Southridge Video;Regular;82 77;179                                                               99;1602;Filme DVD
Southridge Video;Regular;73 57;159                                                               99;1606;Filme DVD
Southridge Video;Regular;82 77;179                                                               99;1607;Filme DVD
Southridge Video;Regular;73 57;159                                                               99;1611;Filme DVD
Southridge Video;Regular;82 77;179                                                               99;1612;Filme DVD

[1690 rows x 1 columns]

In [3]:
import pandas as pd

vendas_df = pd.read_csv('Contoso - Cadastro Produtos.csv')

vendas_df

                                                                Nome da Marca;Tipo;Custo Unitario;Preco Unitario;ID Produto;Categoria
Contoso;Econômico;10        69;20                                                 96;873;Acessório para Computador
Contoso;Econômico;6         63;13;879;Acessório para Computador                                                NaN
                            63;13;880;Acessório para Computador                                                NaN
                            63;13;881;Acessório para Computador                                                NaN
                            63;13;882;Acessório para Computador                                                NaN
...                                                                                                            ...
Southridge Video;Regular;82 77;179                                                               99;1602;Filme DVD
Southridge Video;Regular;73 57;159                                                               99;1606;Filme DVD
Southridge Video;Regular;82 77;179                                                               99;1607;Filme DVD
Southridge Video;Regular;73 57;159                                                               99;1611;Filme DVD
Southridge Video;Regular;82 77;179                                                               99;1612;Filme DVD

[1690 rows x 1 columns]

In [ ]:
#csv as celulas sao separadas por ',' e nessa planilha os dados estão separados por ';' logo devemos especificar isso
import pandas as pd

vendas_df = pd.read_csv('Contoso - Cadastro Produtos.csv', sep= ';') #também pode colar o caminho do arquivo

vendas_df

,Nome da Marca,Tipo,Custo Unitario,Preco Unitario,ID Produto,Categoria
0,Contoso,Econômico,"10,69","20,96",873,Acessório para Computador
1,Contoso,Econômico,"6,63",13,879,Acessório para Computador
2,Contoso,Econômico,"6,63",13,880,Acessório para Computador
3,Contoso,Econômico,"6,63",13,881,Acessório para Computador
4,Contoso,Econômico,"6,63",13,882,Acessório para Computador
...,...,...,...,...,...,...
1685,Southridge Video,Regular,"82,77","179,99",1602,Filme DVD
1686,Southridge Video,Regular,"73,57","159,99",1606,Filme DVD
1687,Southridge Video,Regular,"82,77","179,99",1607,Filme DVD
1688,Southridge Video,Regular,"73,57","159,99",1611,Filme DVD
1689,Southridge Video,Regular,"82,77","179,99",1612,Filme DVD